name: Pytest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy build

    - name: Install batchstats
      run: |
        python -m build
        pip install .

    - name: Run Pytest
      run: |
        pytest tests/test_merge.py
        pytest tests/test_nanstats.py
        pytest tests/test_stats.py